data:
    path: '/data/deepvk/librispeech/train_clean_100/train-clean-100'
    waveform_len: 20480
    
model:
    predict_steps: 12
    context_size: 256
    conv_channels: 512
    
    
train:
    lr: 0.0002
    batch_size: 10
    epochs: 5
    save_every: 1
    save_name: 'ctc_model'