data:
    path: '/data/deepvk/librispeech/dev_clean/dev-clean'
    lexicon: '/data/deepvk/librispeech-lexicon.txt'
    waveform_len: 20480

model:
    cpc_config_path: 'GIL_model/config.yaml'
    hidden_size: 256
    freeze_cpc_model: False

train:
    lr: 0.02
    epochs: 100
    save_every: 2
    test_split: 0.15
    batch_size: 3
    shuffle_data: True
    save_name: 'phone_cpc_nce_classifier'
    checkpoints_dir: 'cluster_checkpoints'
    device: 'cuda:0'
    load_cpc_checkpoint: False
    cpc_checkpoint: 'cpc_nce_model_ctz_15_epoch.pt'
