data:
    path: '/data/deepvk/librispeech/dev_clean/dev-clean'
    waveform_len: 20480

model:
    cpc_config_path: 'GIL_model/config.yaml'
    hidden_size: 256
    freeze_cpc_model: True

train:
    lr: 0.01
    epochs: 100
    save_every: 10
    test_split: 0.1
    batch_size: 23
    shuffle_data: True
    save_name: 'speaker_grad_isolated_model'
    checkpoints_dir: 'cluster_checkpoints'
    device: 'cuda:0'
    cpc_checkpoint: 'grad_isolated_model_12_epoch.pt'
